name: release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build-linux:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        make
        tar cavf ccodoc-linux.tar.gz ccodoc
    - name: upload ccodoc
      uses: actions/upload-artifact@v3
      with:
        name: ccodoc-linux.tar.gz
        path: ccodoc-linux.tar.gz
        if-no-files-found: error

  build-macos:
    needs: ["test"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: brew install ncurses
    - name: build
      run: |
        make LDFLAGS=-L/usr/local/opt/ncurses/lib
        tar cavf ccodoc-macos.tar.gz ccodoc
    - name: upload ccodoc
      uses: actions/upload-artifact@v3
      with:
        name: ccodoc-macos.tar.gz
        path: ccodoc-macos.tar.gz
        if-no-files-found: error

  release:
    needs: ["build-linux", "build-macos"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: download ccodoc/linux
      uses: actions/download-artifact@v3
      with:
        name: ccodoc-linux.tar.gz
    - name: download ccodoc/macos
      uses: actions/download-artifact@v3
      with:
        name: ccodoc-macos.tar.gz
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ccodoc-linux.tar.gz
          ccodoc-macos.tar.gz
        draft: true
        tag_name: ${{ github.ref_name }}
