name: release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build-linux:
    needs: ["test"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make
    - name: upload ccodoc
      uses: actions/upload-artifact@v3
      with:
        name: ccodoc-${{ github.ref_name }}-linux
        path: ccodoc
        if-no-files-found: error

  build-macos:
    needs: ["test"]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: brew install ncurses
    - name: build
      run: make LDFLAGS=-L/usr/local/opt/ncurses/lib
    - name: upload ccodoc
      uses: actions/upload-artifact@v3
      with:
        name: ccodoc-${{ github.ref_name }}-macos
        path: ccodoc
        if-no-files-found: error

  release:
    needs: ["build-linux", "build-macos"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: download ccodoc/linux
      uses: actions/download-artifact@v3
      with:
        name: ccodoc-${{ github.ref_name }}-linux
        path: ./ccodoc-${{ github.ref_name }}-linux
    - name: download ccodoc/macos
      uses: actions/download-artifact@v3
      with:
        name: ccodoc-${{ github.ref_name }}-macos
        path: ./ccodoc-${{ github.ref_name }}-macos
    - name: draft-release
      uses: softprops/action-gh-release@v1
      with:
        files: ./ccodoc-${{ github.ref_name }}-linux ./ccodoc-${{ github.ref_name }}-macos
        draft: true
        tag_name: ${{ github.ref_name }}
